#!/usr/bin/env python
# Copyright 2013 Ben Ockmore

# This file is part of WavePlot.

# WavePlot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# WavePlot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with WavePlot. If not, see <http://www.gnu.org/licenses/>.

import subprocess
import zlib
import base64
import requests
import mutagen
import os
import sys
import time
import datetime
import json
import sqlite3 as db
import re
import uuid

VERSION = u"CITRUS"
LAST_RUN = u"2013-05-25 21:37"

_console_encoding = sys.stdout.encoding
def safeprint(str_to_print):
    """Encode unicode strings to filesystem encoding."""
    if isinstance(str_to_print, unicode):
        print str_to_print.encode(_console_encoding, 'replace')
    else:
        print unicode(str_to_print).encode(_console_encoding, "replace")  # Assume string is ascii.


def set_waveplot_paths():
    global config_path, data_path

    if sys.platform == "linux2":
        config_path = os.path.realpath(os.path.expanduser(u"~/.config"))
        data_path = os.path.realpath(os.path.expanduser(u"~/.local/share"))
    elif sys.platform == "win32":
        config_path = data_path = os.path.realpath(unicode(os.environ['APPDATA']))

    if (config_path == None) or (not os.path.exists(config_path)):
        config_path = os.path.realpath(os.path.dirname(__file__))
    else:
        config_path = os.path.join(config_path, u"waveplot")

    if (data_path == None) or (not os.path.exists(data_path)):
        data_path = os.path.realpath(os.path.dirname(__file__))
    else:
        data_path = os.path.join(data_path, u"waveplot")

    try:
        os.makedirs(config_path)
        os.makedirs(data_path)
    except OSError:
        pass

    config_path = os.path.join(config_path, u"waveplot.conf")
    data_path = os.path.join(data_path, u"waveplot.db")


def check_and_read_config():
    global config
    if not os.path.exists(config_path):
        # First time running
        safeprint ("It looks like this is the first time you've run the script. Please follow the following instructions to get started!\n")
        safeprint ("1. Firstly, you'll need to enter your editor key. This is the number at the end of the link in your activation email. Please enter it below.")

        config['editor_key'] = raw_input("Activation Key: ")
        config['server'] = "http://pi.ockmore.net:19048"
        config['max_http_attempts'] = 3
        config['updates'] = { 'repo_url' : "https://raw.github.com/LordSputnik/waveplot-client",
                              'update_branch' : "alpha" }

        safeprint ("\nThat's it for now! WavePlot will now scan the current working directory, and let you know how it's getting on from time to time. Simple set-ups are so good, right?")

        with open(config_path, "wb") as config_file:
            json.dump(config, config_file, sort_keys = True, indent = 4, separators = (',', ': '))

    else:
        with open(config_path, "rb") as config_file:
            config = json.load(config_file)


def check_and_open_db():
    global db_conn
    db_conn = db.connect(data_path)
    db_conn.row_factory = db.Row

    c = db_conn.cursor()
    try:
        c.execute('SELECT file_path, waveplot_id, version, date FROM scanned_files LIMIT 1')
    except db.OperationalError:
        # Drop the table, create new one.
        c.execute("DROP TABLE IF EXISTS scanned_files")
        c.execute("CREATE TABLE scanned_files (file_path TEXT PRIMARY KEY, waveplot_id TEXT, version TEXT, date INTEGER)")
        db_conn.commit()

def GetLastRunValue(script_str):
    find_str = "LAST_RUN" + " = u\""
    start = script_str.find(find_str)

    if start == -1:
        return None

    start += len(find_str)
    end = script_str.find("\"", start)

    return script_str[start:end]


def auto_update():
    remote_script = requests.get(u"{}/{}/{}".format(config['updates']['repo_url'], config['updates']['update_branch'], u"waveplot.py")).content

    remote_last_run = GetLastRunValue(remote_script)

    if remote_last_run is None:
        return

    remote_last_run = datetime.datetime.strptime(remote_last_run[0:16], "%Y-%m-%d %H:%M")

    local_last_run = datetime.datetime.strptime(LAST_RUN[0:16], "%Y-%m-%d %H:%M")

    if local_last_run < remote_last_run:
        update_now = ""
        while (update_now != "y") and (update_now != "n"):
            update_now = raw_input("Update ready! ({}) Apply? (y/n) ".format(remote_last_run))

        if update_now.lower() == "y":
            print "Updating! Please wait..."

            with open(__file__, "wb") as local_script:
                local_script.write(remote_script)

            os.execl(__file__)


def find_imager():
    global imager_exe

    # First, imager should be in ../imager directory, relative to scanner.py.
    scanner_dir = os.path.realpath(os.path.dirname(__file__))
    imager_dir = os.path.realpath(os.path.join(scanner_dir, u"imager"))

    # Make sure the directory exists
    if os.path.exists(imager_dir):
        for filename in os.listdir(imager_dir):
            if filename == imager_exe:
                imager_exe = os.path.realpath(os.path.join(imager_dir, filename))
                return

    # If not, check the scanner dir itself.
    for filename in os.listdir(scanner_dir):
        if filename == imager_exe:
            imager_exe = os.path.realpath(os.path.join(scanner_dir, filename))
            return

    # Otherwise, assume it can just be called as "WaveplotImager" or "WaveplotImager.exe"
    safeprint("Unable to locate WavePlotImager in script directory - assuming it's in PATH.")

    safeprint("Checking for existence of WavePlotImager...")

    try:
        subprocess.call([imager_exe.encode("UTF-8"), ])
    except OSError:
        safeprint("Error: Could not find WavePlotImager.")
        imager_exe = None

    return


def WavePlotPost(url, values):
    attempts = 0
    while attempts < config['max_http_attempts']:
        try:
            r = requests.post(url, data = values)
        except requests.ConnectionError:
            attempts += 1
            time.sleep(0.5)
        else:
            return r.json()

    return None

def submit_imager_output(output):
    split_data = re.split(r"WAVEPLOT_START|WAVEPLOT_DR|WAVEPLOT_INFO|WAVEPLOT_END", output)

    if len(split_data) == 5:
        image_data, dr_level, info = split_data[1:4]

        encoded_image = base64.b64encode(zlib.compress(image_data))

        length, trimmed, sourcetype, num_channels = info.split("|")

        url = config['server'] + '/json/waveplot'

        values = {'recording' : recording_id,
                  'release' : release_id,
                  'track' : track_num,
                  'dr_level' : dr_level,
                  'disc' : disc_num,
                  'image' : encoded_image,
                  'editor' : config['editor_key'],
                  'length' : length,
                  'trimmed' : trimmed,
                  'source' : sourcetype,
                  'num_channels': num_channels,
                  'version' : VERSION }

        result = WavePlotPost(url, values)

        if result[u'result'] == u'failure':
            safeprint(result[u'error'])
            return None
        else:
            return result[u'uuid']

# --- Main Script --- #
if __name__ == "__main__":

    config_path = None
    data_path = None

    config = {}

    db_conn = None

    dir_has_audio = False

    imager_exe = u"WavePlotImager"
    if sys.platform == "win32":
        imager_exe += u".exe"

    set_waveplot_paths()
    check_and_read_config()
    check_and_open_db()

    auto_update()

    find_imager()

    if imager_exe is None:
        sys.exit(1)

    safeprint(u"Using executable: {}".format(imager_exe))

    imager_exe = imager_exe.encode("utf_8")
    VERSION = VERSION.encode("utf_8")

    safeprint(u"\nFinding files to scan...")

    c = db_conn.cursor()

    for directory, directories, filenames in os.walk(u"."):

        if dir_has_audio:
            safeprint("")

        safeprint(directory)
        dir_has_audio = False

        for filename in filenames:

            in_path = os.path.realpath(os.path.join(directory, filename))

            audio = mutagen.File(os.path.join(directory, filename), easy = True)

            if audio:
                recording_id = audio.get("musicbrainz_trackid", [None, ])[0]
                release_id = audio.get("musicbrainz_albumid", [None, ])[0]
                track_num = audio.get("tracknumber", [None, ])[0]
                disc_num = audio.get("discnumber", [None, ])[0]

                if (recording_id is not None) and (release_id is not None) and (track_num is not None) and (disc_num is not None):
                    dir_has_audio = True

                    track_num = track_num.split(u'/')[0].strip()
                    disc_num = disc_num.split(u'/')[0].strip()

                    c.execute("SELECT * FROM scanned_files WHERE file_path=?", (in_path,))
                    result = c.fetchone()

                    if result is not None:
                        if (result['version'] == VERSION) and (result['waveplot_id'] is not None):
                            sys.stdout.write(u"#".encode(sys.stdout.encoding, "replace"))
                            sys.stdout.flush()
                            continue

                    safeprint(u"File: {}".format(in_path))

                    try:
                        output = subprocess.check_output([imager_exe, in_path.encode('utf_8'), VERSION])
                    except subprocess.CalledProcessError:
                        safeprint("WavePlotImager Error - Skipped File.")
                    else:
                        result = submit_imager_output(output)
                        
                        print result

                        c.execute("INSERT OR REPLACE INTO scanned_files VALUES (?,?,?,?)", (in_path, result, VERSION, datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M")))
                        db_conn.commit()

    db_conn.close()
