CC = g++
CFLAGS = -std=c++11 -c -O2 -DWIN32
ODIR = obj
_OBJS = audio.o main.o error.o
OBJS = $(patsubst %,$(ODIR)/%,$(_OBJS))
LINK_OPTS = -L/local/lib -lavformat -lavcodec -lavutil -lz -static-libgcc -static-libstdc++
OUT = WavePlotImager.exe
INCLUDE= -I/local/include

all : $(OBJS)
	$(CC) $(OBJS) -o $(OUT) $(LINK_OPTS)

$(ODIR)/%.o : %.cpp $(ODIR)
	$(CC) $(CFLAGS) $(INCLUDE) -o $@ $<

$(ODIR):
	mkdir $(ODIR)

.PHONY: clean

clean:
	rm -f $(ODIR)/*.o $(OUT)

